DAPS-860 Revised staking status widget
TheArcadiaGroup/DAPS pull request #389
Opened 2019-09-11 22:52 UTC by pedrorv0106

2019-09-13 22:26 UTC, lyricidal approved these changes

2019-09-13 22:34 UTC, lyricidal requested changes
Looks like we are missing one state:

*    Disabling staking… (with grey indicator)

This works:
```
void BitcoinGUI::setStakingInProgress(bool inProgress)
{
	if (inProgress) {
        stakingState->setText(tr("Enabling staking..."));
        stakingAction->setIcon(QIcon(":/icons/staking_active"));
	} else {
        stakingState->setText(tr("Disabling staking..."));
        stakingAction->setIcon(QIcon(":/icons/staking_inactive"));
	}
}
```

Also keeping in mind:

```
    if (pwalletMain) {
        fMultiSend = pwalletMain->isMultiSendEnabled();
        stkStatus = pwalletMain->ReadStakingStatus();
        if(pwalletMain->walletStakingInProgress) {
          if (nLastCoinStakeSearchInterval == 0) {
            return;
          }
        }
    }
```

This return in the if statement is preventing the indicator from switching to Staking disabled

2019-09-14 13:49 UTC, lyricidal approved these changes

2019-09-14 16:30 UTC, DecentralizedSolutions approved these changes

2019-09-14 16:30 UTC, merged